version: "3"

services: 
    
    myreactapp:
        
        build: 
            dockerfile: Dockerfile
            context: ./client
        ports: 
            - 3000:3000
        restart: always
        networks: 
            - numer
   

volumes:
    db_data:
networks: 
    numer: 